### ISSUE TITLE
[Docker] multi-stages

### ISSUE THREAD

**Issue by GuillaumeDua** [GuillaumeDua/cpp-toolchain#3]
multi-stages:

- [ ] build only
- [ ] run only
- [ ] (dev-only) vscode integration
- [ ] (dev/staging-only) ssh-support
- [ ] static analysis tools

See also #1 

---

Integration:

- [stop-at-a-specific-build-stage](https://docs.docker.com/build/building/multi-stage/#stop-at-a-specific-build-stage)
- and/or `--target` to build a specific stage (`target:` in Dockerfile)

```yaml
version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
```
